BET/urls.py
from atexit import register
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("register.urls", namespace="register")),

    path("play", include("workbench.urls", namespace="play"))
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    
    path('signup', views.signup, name="signup"),
    path('login', views.logging_in, name="login"),
    path('logout', views.logging_out, name="logout"),
]

workbench/urls.py
from django.urls import path
from . import views

app_name = "workbench"

urlpatterns = [
    path('homepage', views.homepage, name="homepage"),

    path('slip', views.slip_page, name="slip"),

    path('game-UpdateDetail/<str:pk>', views.game_UpdateView, name="game-update-detail"),
    
    path('slip/<str:pk>game-removal', views.slip_removal, name="slip-game-remove")
]

register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

workbench/models.py
from calendar import c
from telnetlib import GA
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime

User = get_user_model()


class Game(models.Model):
    GAME_CHOICES = (
        ("Football", "Football"),
        ("Basketball", "Basketball"),
    )

    name = models.CharField(max_length=250, choices=GAME_CHOICES)

    gameID = models.CharField(max_length=50) #this means game's unique identity key.

    player1 = models.CharField(max_length=250)
    player2 = models.CharField(max_length=250)
    
    player1_odd = models.FloatField()
    player2_odd = models.FloatField()
    draw_odds = models.FloatField()

    created_on = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name + ": " + self.player1 + " VS " + self.player2


class GameResult(models.Model):
    game = models.OneToOneField(Game, on_delete=models.CASCADE)

    PREDICTION_CHOICES = (
        ("1x", "1x"),
        ("x2", "x2"),
        ("Draw", "Draw"),
    )

    game_result = models.CharField(max_length=25, choices=PREDICTION_CHOICES)

    def __str__(self):
        return self.game.name + ": " + self.game.player1 + " VS " + self.game.player2 + " (" + self.game_result + ")"



class Slip(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    picked_game = models.ForeignKey(Game, on_delete=models.CASCADE)

    USER_PREDICTIONS = (
        ("1x", "1x"),
        ("x2", "x2"),
        ("Draw", "Draw"),
    )

    predict = models.CharField(max_length=25, choices=USER_PREDICTIONS)
    slip_creation = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.user.username + ": " + self.picked_game.name + " -- " + self.picked_game.player1 + " VS " + self.picked_game.player2 + " (" + self.predict + ")" 



class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    selected_game = models.ForeignKey(Game, on_delete=models.CASCADE)
    ticket_code = models.CharField(max_length=10)

    TICKET_OPTIONS = (
        ("Won", "Won"),
        ("Lost", "Lost"),
        ("Void", "Void"),
    )

    ticket_option = models.CharField(max_length=10, choices=TICKET_OPTIONS)
    ticket_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return "Ticket: " + self.ticket_code + " " + self.user + " on " + self.ticket_date

workbench/forms.py
from django import forms
from .models import Slip


# class SlipCreationForm(forms.ModelForm):
#     class Meta:
#         model = Slip
#         fields = (
#             'predict',
#         )

class GameEditForm(forms.ModelForm):
    class Meta:
        model = Slip
        fields = (
            "predict",
        )

register/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import User


def landing_page(request):
    return render(request, 'landing_page.html')


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if len(email) > 0:

            if len(username) > 0:

                if len(password1) > 0:

                    if password1 == password2:
                        if User.objects.filter(email=email).exists():
                            messages.info(request, 'Email address already exists')
                            return redirect('register:signup')

                        elif User.objects.filter(username=username).exists():
                            messages.info(request, 'username already exists')
                            return redirect('register:signup')

                        else:
                            new_user = User.objects.create_user(username=username, password=password1, email=email,
                                                                        first_name=first_name, last_name=last_name)
                            new_user.save()
                            return redirect('register:login')
                    else:
                            messages.info(request, 'Passwords do not match')
                            return redirect('register:signup')
                else:
                    messages.info(request, 'Password field required')
                    return redirect('register:signup')
            else:
                messages.info(request, 'username field required')
                return redirect('register:signup')
            
        else:
            messages.info(request, 'Email field required')
            return redirect('register:signup')

    else:
        return render(request, "register/signup.html")


def logging_in(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('play:homepage')
        else:
            messages.info(request, 'Invalid username/password')
            return redirect('register:login')

    else:
        return render(request, "register/login.html")


def logging_out(request):
    logout(request)
    return redirect('register:login')

workbench/views.py
from django.shortcuts import render, redirect
from .models import Game, Slip
from .forms import GameEditForm
from django.contrib import messages


def slip_page(request):
    slip = Slip.objects.all()
    game = Game.objects.all()

    if request.method == "POST":
        pass

    return render(request, "workbench/slip.html", {"slip": slip})


def homepage(request):
    game = Game.objects.all()
    return render(request, "workbench/homepage.html", {"game": game})



def game_UpdateView(request, pk):
    game = Game.objects.get(id=pk)
    slip = Slip.objects.all()

    current_user = request.user

    form = GameEditForm()

    if request.method == "POST":

        if Slip.objects.filter(picked_game=game).exists():
            up_slip = Slip.objects.get(picked_game=game)
            form = GameEditForm(request.POST, instance=up_slip)

            if form.is_valid():
                form.save()

                messages.success(request, 'Slip update successful')
                return redirect('play:slip')

            else:
                return redirect('play:homepage')

        else:
            form = GameEditForm(request.POST)

            if form.is_valid():
                prediction = form.cleaned_data['predict']

                new_slip = Slip.objects.create(user=current_user, picked_game=game, predict=prediction)
                new_slip.save()

                messages.success(request, "Upload success!")
                return redirect('play:homepage')
            
            else:
                return redirect('play:homepage')

    else:
        return render(request, "workbench/game_select_update.html", {"game": game, "form": form, "slip": slip})


def slip_removal(request, pk):
    slip = Slip.objects.get(id=pk)
    slip.delete()

    messages.info(request, 'game has been removed')
    return redirect('play:slip')

register/templates/register/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}

    {% for message in messages %}
        <p style="color: red;">{{message}}</p>
    {% endfor %}

    <p>Username: <input type="text", name="username"></p>
    <p>Password: <input type="password", name="password"></p>

    <input type="submit", value="login">

</form>

{% endblock %}

register/templates/register/signup.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}

    {% for message in messages %}
        <p style="color: red;">{{message}}</p>
    {% endfor %}

    <p>Username: </p>
    <input type="text", name="username">

    <p>First Name: </p>
    <input type="text", name="first_name">

    <p>Last Name:</p>
    <input type="text", name="last_name">

    <p>Email: </p>
    <input type="email", name="email">

    <p>Password: </p>
    <input type="password", name="password1">

    <p>Confirm Password: </p>
    <input type="password", name="password2">

    <br>
    <br>
    <input type="submit", value="Register">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Betsite</title>
</head>

<body>

    {% include 'navbar.html' %}

        <div class="game-page">
            {% block content %}
            {% endblock %}
        </div>

    </div>

</body>

</html>

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}

    <h2>Welcome to the landing page</h2>

    {% if request.user.is_anonymous %}

    <h2>Proceed To Login</h2>

    {% endif %}

{% endblock %}

templates/navbar.html
<hr>

<h1>MORAKS-SITE</h1>

{% if request.user.is_anonymous %}

    <a href="{% url 'register:login' %}"><button> Login </button></a>

    <a href="{% url 'register:signup' %}"><button> Signup </button></a>


{% elif request.user.is_authenticated %}
    
    <a href="{% url 'play:homepage' %}"><button> Home </button></a>
    <a href="{% url 'play:slip' %}"><button> Slip </button></a>
    <a href=""><button> Ticket </button></a>

    <a href=""><button> Profile </button></a>
    <a href="{% url 'register:logout' %}"><button> Logout </button></a>

{% endif %}

<hr>

workbench/templates/workbench/game_select_update-detail.html
{% extends 'base.html' %}

{% block content %}

<p style="font-size: 50px;">{{ game.player1 }} VS {{ game.player2 }}</p>

{% for slip in slip %}

    {% comment %} {% if request.user.username == slip.user.username %}
        <p>You selected "{{ slip.predict }}" for this game</p>  
    {% endif %} {% endcomment %}

{% endfor %}

<form method="post">

    {% csrf_token %}

    <div style="font-size: 30px;">
        {{ form.as_p }}
    </div>

    <input type="submit", value="submit">

</form>


{% endblock %}

workbench/templates/workbench/game_select_update.html
{% extends 'base.html' %}

{% block content %}


<p style="font-size: 50px;">{{ game.player1 }} VS {{ game.player2 }}</p>


{% for slip in slip %}
    {% if slip.picked_game == game  %}
        <div style="font-size: 25px;">
            Selected: {{ slip.predict }}
        </div>
    {% endif %}
{% endfor %}


<form method="post">

    {% csrf_token %}

    <div style="font-size: 30px;">
        {{ form.as_p }}
    </div>

    <input type="submit", value="submit">

</form>


{% endblock %}

workbench/templates/workbench/homepage.html
{% extends 'base.html' %}

{% block content %}

    {% for message in messages %}
    <div style="color: green;">
        {{ message }}
    </div>
    {% endfor %}

    {% for game in game reversed%}
        
        {% if game.name == "Football" %}
        <h2 style="text-decoration: underline;">Football</h2>
        <ul>
            <li>
                <a href="{% url 'play:game-update-detail' game.id %}", style="text-decoration: none; color: black;">
                    <p style="font-size: 20px;">{{ game.player1 }} VS {{ game.player2 }}</p>
                </a>
            </li>
        </ul>

        {% elif game.name == "Basketball" %}
        <h2 style="text-decoration: underline;">Basketball</h2>
        <ul>
            <li>
                <a href="{% url 'play:game-update-detail' game.id %}", style="text-decoration: none; color: black;">
                    <p style="font-size: 20px;">{{ game.player1 }} VS {{ game.player2 }}</p>
                </a>
            </li>
        </ul>

        {% endif %}

    {% endfor %}

{% endblock %}

workbench/templates/workbench/slip.html
{% extends 'base.html' %}

{% block content %}

    {% for message in messages %}
        <div style="color: green;">
            {{ message }}
        </div>
    {% endfor %}

    {% if request.user.is_authenticated %}

        <h2 style="text-decoration: underline;">Game Slip</h2>


        {% for slip in slip %}
            <hr>
            <div>
                <a href="{% url 'play:game-update-detail' slip.picked_game.id %}", style="text-decoration: none; color: black;">

                    <p style="font-size: 20px;">{{ slip.picked_game.player1 }} VS {{ slip.picked_game.player2 }}</p>
                    <p style="font-size: 18px;">Selected: {{ slip.predict }}</p>
                    <p style="font-size: 15px;">{{ slip.picked_game.name }}</p>

                </a>
                <br>

                <div>
                    <a href="{% url 'play:slip-game-remove' slip.id %}"><button> Remove </button></a>
                </div>
            </div>

            <hr>

        {% endfor %}



        <form method="post"> 
            {% csrf_token %} 

            <div>
                <input type="number", placeholder="NGN 0.00", name="staked_amount">
                <input type="submit", value="Stake", name="stake">
            </div>

        </form>


    {% endif %}

{% endblock %}